services:
  db:
    image: dockerhub.timeweb.cloud/library/postgres:16
    container_name: project_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    networks:
      - app_network
    # --- ДОБАВЛЯЕМ ПРОВЕРКУ ЗДОРОВЬЯ БАЗЫ ---
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 5

  web:
    build: .
    container_name: project_app
    restart: always
    ports:
      - "${APP_PORT}:8000"
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    environment:
      - UVICORN_RELOAD=True
    # --- ОБНОВЛЯЕМ ЗАВИСИМОСТЬ ---
    depends_on:
      db:
        condition: service_healthy  # Ждать полной готовности Postgres принимать соединения
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
