services:
  db:
    # Указываем прокси напрямую в имени образа
    image: dockerhub.timeweb.cloud/library/postgres:16
    container_name: project_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./.pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: project_app
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./app:/app/app  # Связывает вашу локальную папку app с папкой внутри контейнера
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - UVICORN_RELOAD=True
    depends_on:
      - db